name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  security_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install program dependencies
        run: npm install
      - name: Fix modules
        run: npm audit fix --force
      - name: Run the project
        run: npm run start &
      - name: Run integration tests
        run: npm audit

  build_test:
    runs-on: ubuntu-latest
    needs: security_test

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install program dependencies
        run: npm install
      - name: Fix modules
        run: npm audit fix --force
      - name: Run the project
        run: npm run start &
      - name: Run integration tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
