name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    srategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install program dependencies
        run: npm install
      - name: Fix modules
        run: npm audit fix --force
      - name: Run the project
        run: npm run start &
      - name: Run integration tests
        run: npm run test
